### ISSUE TITLE
Exception on /browser_profiles [GET]

### ISSUE THREAD

**Issue by Garasum** [yagiraa/dolphin-free#11]
Greetings @yagiraa  
After Closing Anty and restarting the computer browser profiles are no longer loading ( Status code 500 , NotADirectoryError: [Errno 20] Not a directory: '/Users/orestharasym/PycharmProjects/dolphin-free/browsers/.DS_Store/info_for_start.json'

System : Apple M1 Pro , Mac OS 13.3.1 , Latest Github Commit 
Remote Anty has only 4 profiles

Full Stack trace : 
```
ERROR in app: Exception on /browser_profiles [GET]
Traceback (most recent call last):
  File "/Users/orestharasym/PycharmProjects/dolphin-free/venv1/lib/python3.10/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/orestharasym/PycharmProjects/dolphin-free/venv1/lib/python3.10/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/orestharasym/PycharmProjects/dolphin-free/venv1/lib/python3.10/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/orestharasym/PycharmProjects/dolphin-free/venv1/lib/python3.10/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/orestharasym/PycharmProjects/dolphin-free/utils.py", line 62, in wrapper
    ret_val = func(*args, **kwargs)
  File "/Users/orestharasym/PycharmProjects/dolphin-free/main.py", line 157, in browser_profiles
    profile_info = Files.read_from_file(f'browsers/{i}/info_for_start.json')
  File "/Users/orestharasym/PycharmProjects/dolphin-free/modules/files.py", line 25, in read_from_file
    with open(os.path.join(cls.cwd, file), 'r') as f:
NotADirectoryError: [Errno 20] Not a directory: '/Users/orestharasym/PycharmProjects/dolphin-free/browsers/.DS_Store/info_for_start.json'
```

**Comment by Garasum** [comment]
Fixed by downloading the fresh version from repository and copy-ing the browser profiles

Still wondering what could go wrong and is there another solution (like clearing the cache )

**Comment by primeboo** [comment]
here my simple solution before everythong was stuck with INTERFACE iSSUE

1) start the anti
2) log in
3) you should have a t list 1 profile
4) !!!! dont log out!!!! just close ANTI
5) start main.py
6) start ANTI

profit 


just lets wait for patching last issue with interface mistake
